preload = ~/Pictures/sys-images/berserk.jpg
wallpaper {
    monitor = DP-2
    path = ~/Pictures/sys-images/berserk.jpg
    fit_mode = cover
} 
# notebook:
wallpaper {
    monitor = eDP-1
    path = ~/Pictures/sys-images/berserk.jpg
    fit_mode = cover
} 

splash = false
